library ieee;
use ieee.std_logic_1164.all;

--------------------------------------------------------------------------------
-- DUT wrapper for scan chain testing -- generated by scripts/new_lab.py
-- from StringDetector.vhdl, entity StringDetector.
--
-- Tracefile bit layout, MSB-first as written in the file:
--
--   input_vector(6 downto 2)     = inp
--   input_vector(1)              = reset
--   input_vector(0)              = clock
--
--   output_vector(0)             = outp
--
-- Set in hdl/TopLevel.vhd:
--   number_of_inputs  := 7
--   number_of_outputs := 1
--
-- This comment is the only record of the bit mapping -- it cannot be
-- recovered from the tracefile. Keep it with the file.
--------------------------------------------------------------------------------

entity DUT is
  port (
    input_vector  : in  std_logic_vector(6 downto 0);
    output_vector : out std_logic_vector(0 downto 0)
  );
end entity DUT;

architecture Structural of DUT is

  component StringDetector is
    port (
      inp           : in  std_logic_vector(4 downto 0);
      reset         : in  std_logic;
      clock         : in  std_logic;
      outp          : out std_logic
    );
  end component;

begin

  uut : StringDetector
    port map (
      inp            => input_vector(6 downto 2),
      reset          => input_vector(1),
      clock          => input_vector(0),
      outp           => output_vector(0)
    );

end architecture Structural;
