#!/usr/bin/env python3
"""
Generate TRACEFILE.txt for the Seq1011 example.

Demonstrates the workflow docs/TRACEFILE_FORMAT.md recommends: write a golden
model in Python, drive it with a stimulus stream, and emit the vectors. Typing
a few hundred vectors by hand is how bit-order mistakes get baked into the
expected column.

    python3 examples/seq1011/gen_tracefile.py

Deterministic -- the seed is fixed, so regenerating produces the identical file
and a diff against the committed one is meaningful.

Bit layout, matching DUT.vhd:  < din >< reset >< clock >
"""

import os
import random

SEED = 1011
N_BITS = 300          # stimulus bits; each becomes a clock-low/clock-high pair


def next_state(state, b):
    """Transition function, mirroring Seq1011.vhd's case statement."""
    if state == 0:
        return 1 if b else 0
    if state == 1:
        return 1 if b else 2
    if state == 2:
        return 3 if b else 0
    return 1 if b else 2          # state 3: overlap -- trailing '1' starts anew


def mealy(state, b):
    """Output function: depends on present state AND current input."""
    return 1 if (state == 3 and b == 1) else 0


def golden(bits):
    """
    Produce the expected output for BOTH vectors of each clock pair.

    This is the part that is easy to get wrong, and getting it wrong is
    indistinguishable from a broken harness when the vectors fail on hardware.

    The scan chain applies one input vector and captures one output per vector.
    A clocked DUT therefore needs two vectors per cycle, and a Mealy output is
    *different* in each of them:

      clock low   the rising edge has not happened yet, so the state is still
                  the pre-edge state. mealy(state, b) is the real detection for
                  this input bit.

      clock high  the edge has occurred and the state has advanced. The output
                  is now mealy(next_state(state, b), b) -- same input bit, new
                  state. For a detection this is usually 0, because the FSM has
                  already moved on.

    Writing the same expected value on both lines is the natural first guess and
    it is wrong. The bundled string-detector tracefile shows the correct shape:
    a detection appears as `... 1` on the clock-low line and `... 0` on the
    clock-high line that follows it.

    Returns a list of (expected_low, expected_high) per bit.
    """
    state = 0
    out = []
    for b in bits:
        exp_low = mealy(state, b)          # before the edge
        state = next_state(state, b)       # rising edge
        exp_high = mealy(state, b)         # after the edge, same input applied
        out.append((exp_low, exp_high))
    return out


def main():
    rng = random.Random(SEED)

    # Mostly random, but splice in explicit patterns so the interesting cases
    # are guaranteed present rather than left to chance:
    #   1011      one match
    #   1011011   two overlapping matches
    #   101101011 back-to-back overlaps
    bits = []
    for pattern in ("1011", "1011011", "101101011", "10101010", "1111", "0000"):
        bits += [int(c) for c in pattern]
        bits += [rng.randrange(2) for _ in range(8)]
    while len(bits) < N_BITS:
        bits.append(rng.randrange(2))
    bits = bits[:N_BITS]

    expected = golden(bits)

    here = os.path.dirname(os.path.abspath(__file__))
    path = os.path.join(here, "TRACEFILE.txt")

    with open(path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("# Seq1011 -- overlapping \"1011\" detector\n")
        fh.write("# layout: <din><reset><clock>  expected=<detect>  mask\n")
        fh.write("# generated by gen_tracefile.py, seed %d -- do not hand-edit\n" % SEED)

        # Reset pulse. The output during reset is not meaningful, so mask it
        # off rather than asserting a value we do not actually care about --
        # this is what the mask column is for.
        fh.write("010 0 0\n")           # din=0 reset=1 clock=0
        fh.write("011 0 0\n")           # din=0 reset=1 clock=1  -> state cleared

        for b, (e_lo, e_hi) in zip(bits, expected):
            fh.write(f"{b}00 {e_lo} 1\n")   # clock low, inputs set up
            fh.write(f"{b}01 {e_hi} 1\n")   # clock high, edge occurs

    n = 2 + 2 * len(bits)
    detections = sum(lo for lo, _ in expected)
    print(f"wrote {path}")
    print(f"{n} vectors, 3 in / 1 out, {detections} detections")


if __name__ == "__main__":
    main()
