library ieee;
use ieee.std_logic_1164.all;

--------------------------------------------------------------------------------
-- DUT wrapper for scan chain testing -- generated by scripts/new_lab.py
-- from ALU.vhd, entity ALU.
--
-- Tracefile bit layout, MSB-first as written in the file:
--
--   input_vector(7 downto 4)     = A
--   input_vector(3 downto 0)     = B
--
--   output_vector(5 downto 0)    = Y
--
-- Set in hdl/TopLevel.vhd:
--   number_of_inputs  := 8
--   number_of_outputs := 6
--
-- This comment is the only record of the bit mapping -- it cannot be
-- recovered from the tracefile. Keep it with the file.
--------------------------------------------------------------------------------

entity DUT is
  port (
    input_vector  : in  std_logic_vector(7 downto 0);
    output_vector : out std_logic_vector(5 downto 0)
  );
end entity DUT;

architecture Structural of DUT is

  component ALU is
    port (
      A             : in  std_logic_vector(3 downto 0);
      B             : in  std_logic_vector(3 downto 0);
      Y             : out std_logic_vector(5 downto 0)
    );
  end component;

begin

  uut : ALU
    port map (
      A              => input_vector(7 downto 4),
      B              => input_vector(3 downto 0),
      Y              => output_vector(5 downto 0)
    );

end architecture Structural;
