#!/usr/bin/env python3
"""
Generate an exhaustive TRACEFILE.txt for the ALU example.

    python3 examples/alu/gen_tracefile.py

The ALU is purely combinational with an 8-bit input space, so "exhaustive" is
only 256 vectors -- every possible input, no sampling, no seed. That is the
ideal case for this harness and the reason it exists: 256 vectors by hand is
not happening, 256 vectors over JTAG takes about a second.

Bit layout, matching the generated DUT.vhd:
    input_vector(7 downto 4) = A
    input_vector(3 downto 0) = B
    output_vector(5 downto 0) = Y
"""

import os


def alu(a, b):
    """
    Golden model of ALU.vhd. The operation is selected by the top bit of each
    operand, and the result always lands in Y(3 downto 0) -- Y(5 downto 4) is
    declared but never written by any branch, so it is always "00".
    """
    a3 = (a >> 3) & 1
    b3 = (b >> 3) & 1

    if a3 == 0 and b3 == 0:            # MAX
        if a > b:
            r = a
        elif a < b:
            r = b
        else:
            r = 0                      # equal operands return 0000, not the value
    elif a3 == 1 and b3 == 0:          # ANDER
        r = a & b
    elif a3 == 0 and b3 == 1:          # ROTATOR
        # The branch is only reached when B(3) = '1', and ROTATOR tests B(3)
        # again to choose the direction -- so within this branch it is always
        # a rotate right. The dead rotate-left arm is unreachable.
        n = ((b >> 1) & 1) * 2 + (b & 1)       # B(1) & B(0)
        r = ((a >> n) | (a << (4 - n))) & 0xF if n else a
    else:                              # EQUATOR
        r = a if a == b else 0

    return r & 0xF                     # Y(5 downto 4) stay 0


def main():
    here = os.path.dirname(os.path.abspath(__file__))
    path = os.path.join(here, "TRACEFILE.txt")

    with open(path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("# ALU -- exhaustive: all 256 input combinations\n")
        fh.write("# layout: <A(3:0)><B(3:0)>  expected=<Y(5:0)>  mask\n")
        fh.write("# generated by gen_tracefile.py -- do not hand-edit\n")
        for a in range(16):
            for b in range(16):
                inp = f"{a:04b}{b:04b}"
                exp = f"{alu(a, b):06b}"
                fh.write(f"{inp} {exp} 1\n")

    print(f"wrote {path}")
    print("256 vectors, 8 in / 6 out (exhaustive)")


if __name__ == "__main__":
    main()
